# Settings for the blog

[site]
title = "Sample Blog"
subtitle = "Just Boilerplate"
description = "Just a sample blog"

[build]
buildDirectory = "output"

[templates]
directories = ["templates"]

[pages.posts]
directories = ["posts"]
sortByDate = true
sortReverse = true

[pages.general]
files = ["index.md"]

[assets]
directories = ["assets"]

[generated]
    [generated.tags]
    template = "tags.html"
    iterateOver = "tags"
    path = "tags"

    [generated.tags_index]
    template = "tags.html"
    path = ""